In [ ]:
import numpy as np

## Arrays

In [ ]:
my_list = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]
type(my_list)

list

We can create a numpy array from a Python list

In [ ]:
x = np.array(my_list)
x

array([  1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [ ]:
x.shape #tenemos 12 elementos (x,y)

(12,)

Sometimes it is helpful to reshape our array

In [ ]:
x = x.reshape(-1, 1)
x

array([[  1],
       [  1],
       [  2],
       [  3],
       [  5],
       [  8],
       [ 13],
       [ 21],
       [ 34],
       [ 55],
       [ 89],
       [144]])

In [ ]:
x.shape

(12, 1)

*We* can use the method `len` of the property `shape` to get the number of elements in an array.

In [ ]:
len(x) == x.shape[0]

True

In [ ]:
print(len(x))
print(x.shape[0]) #al ser x.shape(12,1) el 0 es 12, el 1 es 1

12
12


In [ ]:
n = x.shape[0]
n

12

We creare another array of 1s of the same length

In [ ]:
y = np.ones(n)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
y = y.reshape(-1, 1)
y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

Now, let's do some operations between numpy arrays.

In [ ]:
x + y #serie fibonacci, cada serie es la suma de los anteriores

array([[  2.],
       [  2.],
       [  3.],
       [  4.],
       [  6.],
       [  9.],
       [ 14.],
       [ 22.],
       [ 35.],
       [ 56.],
       [ 90.],
       [145.]])

In [ ]:
x + 1 # broadcasting, x +1 más

array([[  2],
       [  2],
       [  3],
       [  4],
       [  6],
       [  9],
       [ 14],
       [ 22],
       [ 35],
       [ 56],
       [ 90],
       [145]])

In [ ]:
x * y

array([[  1.],
       [  1.],
       [  2.],
       [  3.],
       [  5.],
       [  8.],
       [ 13.],
       [ 21.],
       [ 34.],
       [ 55.],
       [ 89.],
       [144.]])

## Multidimensional Arrays

In [ ]:
#Matriz 2 filas x 2 columnas
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
#matriz 3x2
y = np.array([[1, 4], [0, 5], [-1, 1]])
print(y)
print(y.shape)

[[ 1  4]
 [ 0  5]
 [-1  1]]
(3, 2)


In [ ]:
#arreglo de 3 filas x 1 columna
z = np.array([[3], [7], [2]])
print(z)
print(z.shape)

[[3]
 [7]
 [2]]
(3, 1)


In [ ]:
#arreglo 1x2
w = np.array([[1, 12]])
print(w)
print(w.shape)

[[ 1 12]]
(1, 2)


#### Let's do some operations

In [ ]:
x @ y.transpose() # (2, 2) x (2, 3) = (2, 3)

array([[ 9, 10,  1],
       [19, 20,  1]])

In [ ]:
y + z # z is added element-wise in each column of y -> broadcasting  columna 1: (3+1, 3+4),columna 2:(7+0, 7+5), columna 3:(2-1, 2+1)

array([[ 4,  7],
       [ 7, 12],
       [ 1,  3]])

In [ ]:
x + w # w is added element-wise in each row of x -> broadcasting sumar w a cada columna dex

array([[ 2, 14],
       [ 4, 16]])

In [ ]:
np.sum(x)

376

In [ ]:
np.max(x)

144

In [ ]:
np.min(x)

1

In [ ]:
np.max(x, axis=0) #puedo ponerle ,keepdims=True para acomodarlos

array([144])

In [ ]:
np.sum(x, axis=0)

array([376])